### ISSUE TITLE
Damn!

### ISSUE THREAD

**Issue by ItsCEED** [Th3-0b3l1sk/PsPsEye#1]
I left the game long time ago, and i never thought i'd seen open source bot, even with basic functions!

Good job and clean code, im not raelly sure how would you inject this or if it works, but kudos to you!

Edit:
I indeed couldnt resist to test it, but it seems it doesnt work anymore

**Comment by Th3-0b3l1sk** [comment]
Hello,

>  ` but it seems it doesnt work anymore`

You probably have a console output full of " X returned null lpScanAddress.". This is a major issue with memory based bots and bots in general, they require continuous maintenance. I release the bot 5 months ago and didn't touch it after that :). The game had a lot of updates and a recent expansion for archer which messed with functions locations in the game. Although i am using pattern scanning to make it easier to locate the functions, simply by changing the starting address most of the functions will be located. The rest need to be manually inspected since there are many functions with the same signature located next to each other so it's hard find it programmatically.

You can somewhat easily fix this but it requires using a debugger and testing stuff until it works. I think the code is documented enough to help you with this, but if you have any questions, you can DM  [@th3_0bel1sk](https://twitter.com/th3_0bel1sk)

Anyway, you will need to build your own dll since in this release, i believe i disabled auto looting.

As for the injection i use a simple loader that i made but any dll injector will do.

**Comment by ItsCEED** [comment]
As I guessed, it's the code itself (i thought you pushed an update 13 days ago).
And everything you said about the errors you are right and i thought that could be the issue.

I'm far from further developing or fixing this, i was hoping is working to have at least one more full-auto drive on a game that used to be awesome.

overall, your code is clean and documented af. (i cant code C but i do understand it)

**Comment by Th3-0b3l1sk** [comment]
` (i thought you pushed an update 13 days ago).`
Yeah, that's my bad :D. I am new to GitHub and don't know how things work so i included my release folder with the code. someone suggested that i should put it in the releases sections so i just removed the folder from the repository and put it in releases without any modifications :D

` at least one more full-auto drive on a game that used to be awesome.`
i totally agree. it's too bad what happened to this game.

**Comment by ItsCEED** [comment]
Maybe you should consider making this a fully-featured bot which I bet won't be hard of a task since you have all the basics inside.
And offer it on a private sale, cause if it goes public and open to everyone peeps will ruin it

**Comment by Th3-0b3l1sk** [comment]
Thanks for the suggestion!
